name: Deploy to randomchoices.xmit.dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      XMIT_KEY: ${{ secrets.XMIT_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run generate
      - name: Deploy
        run: |
          npm install -g @xmit.co/xmit
          xmit randomchoices.xmit.dev .output/public